name: Generate Documentation

on:
  workflow_call:
    inputs:
      entry-point:
        required: true
        type: string

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{env.NODE_VERSION}}
        registry-url: https://registry.npmjs.org/
    - run: npm i -g npm@latest
    - run: npm clean-install
    - name: Generate Documentation
      id: generate-docs
      run: npx typedoc ${{ inputs.entry-point }}
    - name: Deploy Documentation to Github Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: docs
