name: NPM Package Publish

on:
  workflow_call:
    secrets:
      npm-token:
        required: true
    inputs:
      build-command:
        type: string
        required: false
        default: "npm run build"
      test-command:
        type: string
        required: false
        default: "npm test --if-present"
      
        
env:
  NODEJS_VERSION: 16.20.0

jobs:
  check-is-version-updated:
    runs-on: ubuntu-latest
    steps:
    - uses: MontyD/package-json-updated-action@1.0.1
      id: check-is-version-updated
      with:
        path: package.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  main:
    runs-on: ubuntu-latest
    needs:
      - check-is-version-updated
    if: ${{ needs.check-is-version-updated.steps.check-is-version-updated.outputs.has-updated }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          registry-url: https://registry.npmjs.org/
      - run: npm i -g npm@latest
      - run: npm clean-install
      - run: ${{ inputs.build-command }} 
      - run: ${{ inputs.test-command }}
      - uses: JS-DevTools/npm-publish@v1
        id: publish
        with:
          token: ${{ secrets.npm-token }}
      - name: Create Github Release
        if: steps.publish.outputs.type != 'none'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.publish.outputs.version }}
          release_name: Release ${{ steps.publish.outputs.version }}
          body: ${{ steps.publish.outputs.version }}
          draft: false
          prerelease: false
